### ISSUE TITLE
Need to document system dependencies

### ISSUE THREAD

**Issue by baruchiro** [tsirysndr/tunein-cli#6]
Hi everyone!
I noticed that there are some system dependencies required for this project, but they are not currently documented.
I think it would be helpful to have a list of the required dependencies and instructions on how to install them in the README file.
This would make it easier for new contributors to get started with the project.

In Linux (WSL) I needed to install `libssl-dev`, `pkg-config`, but it still didn't compile.

Thanks for your consideration!

**Comment by tsirysndr** [comment]
Hi there!

Thank you for bringing up this issue and providing valuable feedback. I appreciate your suggestion regarding documenting the system dependencies in the README file. It's indeed important to have clear instructions for new contributors to get started with the project.

 I have carefully considered the suggestions, and I'm happy to let you know that I will also be setting up a Nix development environment to address this issue.

With the Nix package manager, we can ensure consistent and reproducible development environments by defining the required dependencies in a `flake.nix` file.

I will update the README file with instructions on how to use Nix for setting up the development environment and include the necessary details about the required dependencies. This will provide a clear and streamlined process for everyone involved.

Once the Nix setup is complete, contributors can rely on it to manage system dependencies effectively, reducing the chances of compilation errors or missing dependencies.

Thank you for bringing this issue to my attention, and I'm committed to resolving it by implementing the Nix development environment setup. If you have any additional questions, concerns, or suggestions, please feel free to let me know.

Your contributions and support are greatly appreciated!
