### ISSUE TITLE
Is this how the "play" mode should looks like?

### ISSUE THREAD

**Issue by baruchiro** [tsirysndr/tunein-cli#7]
In WSL, compiled from the source, this is the "Play" UI (the audio is OK)

https://github.com/tsirysndr/tunein-cli/assets/17686879/231db4ba-10ce-4232-a5ca-fd34b5cc879a

**Comment by tsirysndr** [comment]
Thank you for bringing this issue to my attention. I appreciate your feedback.

Regarding the current UI , I want to acknowledge that it is a temporary implementation and may not meet everyone's expectations. I am continuously working on improving the UI and welcome any suggestions or ideas you may have.

If you have specific suggestions for enhancing the UI, please feel free to share them. Your input will be valuable in shaping the future improvements of the project. Thank you again for your interest and support.

**Comment by baruchiro** [comment]
Hi, you can see for example the PyRadio interface: https://github.com/coderholic/pyradio
